site_name: Demo Seite von Serafettin
site_url: http://gbs.niederer.swiss/dta23/Serafettin
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
nav:
  - Home: index.md
  - Details: details.md
copyright: 'Version: ${BUILD_VERSION}'